### ISSUE TITLE
Again there's lots of pointer dereferencing everywhere

### ISSUE THREAD

**Issue by izaak-coleman** [korem-lab/pg_collapse_algorithm_cpp#10]
https://github.com/korem-lab/pg_collapse_algorithm_cpp/blob/7c078706bc3b684af251440c5f3aa301fda9f07d/minimizer.cpp#L177

Usually, I just go with: 
1) Pass arguments as const &
2) Make use of RVO and the compiler to return stuff using a move, rather than making a pointer and returning the pointer
```
someObject f(...) {
   someObject obj(...);
   # a bunch of stuff
   return obj;
}
```

the compiler is smart enough to see that obj is made in the function, and returned by it, and doesn't have any complex state stuff attached to it. so, it will just move it out. 

3) if the object's construction is very complex, then pass the object in to the function as a non-const &, modify it, and leave the function as void.

**Comment by eac697** [comment]
This is no longer in the code
