### ISSUE TITLE
I think this may be slow, and probably not necessary 

### ISSUE THREAD

**Issue by izaak-coleman** [korem-lab/pg_collapse_algorithm_cpp#13]
https://github.com/korem-lab/pg_collapse_algorithm_cpp/blob/11a5a2da8f1dfddd6d0f6202999e6aee434bd151/alignment.h#L513

There are a few things here. First, chain_and_backtrack returns a unique_ptr<vector<alignments>>, and to do so, it calls make_unique on an already populated vector. I had a hunch this would result in a copy (since the vector is already storing it's data on the heap, and the vector metadata on the stack, to put an entire vector on the heap, accessed by a pointer would mean you need both the vector metadata, and the vector data on the heap). See this program to confirm that the vector is copied. 

```
// Example program
#include <iostream>
#include<vector>
using namespace std;
int main()
{
    vector<int> v(1000, -1);
    auto pv = make_unique<vector<int>>(v);
    cout << v[0] << endl;
    (*pv)[0] = 7;
    cout << v[0] << ' ' << (*pv)[0] << endl;
}

```

Then, we return the unique_ptr, and dereference it immediately and copy the entire vector from the heap over to the location in thread_aln[i]. We do this, even through we already have an empty vector at thread_aln[i] (see the cython implemenation calls thread_aln[i].insert() copying the contents of the vector<Align> over to the thread_aln[i]). 

So I think this implementation is currently doing two copies, both of which are probably unnecessary. I think the best thing is we actually pass thread_aln[i] by ref into chain_and_backtrack, and make the function void, avoiding unique_ptr. There's just no need to return a vector wrapped in a unique_ptr, since the vector itself already safely takes care of the memory management.

**Comment by eac697** [comment]
this was fixed
