### ISSUE TITLE
Need to implement as done in copangraph.py

### ISSUE THREAD

**Issue by izaak-coleman** [korem-lab/pg_collapse_algorithm_cpp#18]
https://github.com/korem-lab/pg_collapse_algorithm_cpp/blob/11a5a2da8f1dfddd6d0f6202999e6aee434bd151/copangraph.h#L397

A note here on the implementation. 

Edges are constructed by looking at u = interval[i-1], v = interval[i] pairs. Such a contiguous pair imply an edge (u,v) in the graph provided they are on the same contig. Therefore, it is essential that interval is not sorted, or permuted in anyway, as it's ordering encodes the edge information.

**Comment by eac697** [comment]
i added a fix for this
