### ISSUE TITLE
I thikn the use of unextended length is buggy?

### ISSUE THREAD

**Issue by izaak-coleman** [korem-lab/pg_collapse_algorithm_cpp#8]
https://github.com/korem-lab/pg_collapse_algorithm_cpp/blob/7c078706bc3b684af251440c5f3aa301fda9f07d/pe_ext_reader.cpp#L110

In the ExtContig class, the unextended length is not computed and set to 0. There are multiple places where
the GetUnextLength() function is used, and it seems like maybe here, because you cut the string with the remove_first/_last_char functions, the unextended length gets computed incorrectly. I.e, you get the size of the "cut" strings, not the size of the original unextended contig.

**Comment by eac697** [comment]
So there is a bug in ext_contig.h file where GetFwdExt() was returning m_bwd_ext value, which I just fixed. Once it was fixed, I printed out the unextLen, bwd_ and fwd_ext from py and c++ and both outputs were identical.
